### ISSUE TITLE
Anyway I can help

### ISSUE THREAD

**Issue by andrewfblack** [EHylands/homebridge-qolsys#1]
I swapped back to Homebridge from Home Assistant last year and one thing I miss is local Qolsys control.  I used to use the AppDaemon/MQTT Qolsys Plugin for Home Assistant.  Looks like this plugin is pulling data using same Control4 connection.  I see the dump of data from Panel but it doesn't look like any accessories are being made.  If there is any testing I can do to help let me know.  I'm excited for this.

**Comment by EHylands** [comment]
Hi, 
Thank you for reaching out !
I was challenged by someone to write that plugin, but I don't actually own an IQ panel 😂. 

The command 4 integration is fairly straightforward.

Having access to the log file while starting the plugin would be very helpful. It's mostly a question of reassembling and sanithizing JSON packets.

Please let me know if you can provide your log file !

Tnx

**Comment by ifeign** [comment]
Just wanted to say thank you for making this. I’ve been using the original HASS integration, the newer version by XaF just doesn’t want to cooperate with me. I hope that this works out!

**Comment by EHylands** [comment]
> Just wanted to say thank you for making this. I’ve been using the original HASS integration, the newer version by XaF just doesn’t want to cooperate with me. I hope that this works out!

Hi,
Still not totally functional.
Please provide log file if you try to run the plugin so I get solve final issue with json packets.
Tnx

**Comment by ifeign** [comment]
I haven’t had a chance to spin it up, but when I do I’ll provide relevant
info

**Comment by andrewfblack** [comment]
I'll upload a log file for you this week.  Its running and it is outputting info about sensors and actions into log

**Comment by EHylands** [comment]
Great!
In the mean time, just bought a IQ 2 plus panel and should receive it any moment now. Will be easier to debug this way !

**Comment by andrewfblack** [comment]
how much log data do you need?  I have my whole log file but its been running awhile.  
[homebridge.log.txt](https://github.com/EHylands/homebridge-qolsys/files/10299473/homebridge.log.txt)

**Comment by EHylands** [comment]
That's way more than I need 😄

After launching homebridge,the summary info_type jsob packet needs to be read properly to configure all the accessories. 

After proper analysis of that packet, you should get a dump in log file of all the Homebridge accessories to be created.

IQ panel is sending json packet and ACK packet simultaneously and the are all being read separately by the plugin so this is not the issue.

Will work on reading and converting that initial json packet and get back to you !

**Comment by EHylands** [comment]
I see i your log file hat you have a new line (\r\n) in every received json packet.
Just published a new beta version stripping the extra characters. (v0.0.3)

**Comment by EHylands** [comment]
Please try version 0.0.7 if possible.
Tnx

**Comment by andrewfblack** [comment]
Im running the latest version and everything is running great.  All my zones and identified and created.  Response in HomeKit is instant.  This is honestly the best Qolsys integration I’ve seen for Home Bridge or Home Assistant.  Anything else I can do to help?

**Comment by andrewfblack** [comment]
It’s working so well I disable my alarm.com one and went to only this direct intergration.

**Comment by EHylands** [comment]
> Im running the latest version and everything is running great.  All my zones and identified and created.  Response in HomeKit is instant.  This is honestly the best Qolsys integration I’ve seen for Home Bridge or Home Assistant.  Anything else I can do to help? 

Great news !
-Could you report your panel type and firmware version ? Will update documentation accordingly.

- Can you arm-away, disarm and arm-stay through HomeKit ?

**Comment by andrewfblack** [comment]
Arming is working fine but it’s not disarming.  I forgot to test that because my panel disarms auto when my phone comes back home using Bluetooth to panel.  I just check disarming in HomeKit and it’s not working

**Comment by EHylands** [comment]
> Arming is working fine but it’s not disarming. I forgot to test that because my panel disarms auto when my phone comes back home using Bluetooth to panel. I just check disarming in HomeKit and it’s not working

Fixed a typo in Security System accessory. 
Disarmed status state was not handled correctly.
Could you try again with version 0.0.13 ?

**Comment by ifeign** [comment]
> > Arming is working fine but it’s not disarming. I forgot to test that because my panel disarms auto when my phone comes back home using Bluetooth to panel. I just check disarming in HomeKit and it’s not working
> 
> Fixed a typo in Security System accessory. Disarmed status state was not handled correctly. Could you try again with version 0.0.13 ?

Sadly disarming doesn't work for me. IQ2+ running 2.6.1

**Comment by EHylands** [comment]
Typo fixed in 0.0.14:
Probably why error was only occuring while disarming since secure arm is set to false ...
user_code: this.UserPinCode to usercode: this.UserPinCode

**Comment by andrewfblack** [comment]
Working good now I disarmed my house about a dozen times worked every time.  Using a IQ2

**Comment by EHylands** [comment]
> Working good now I disarmed my house about a dozen times worked every time.  Using a IQ2

@andrewfblack Thank you for your help! I will be closing this issue. Please let me know if you need any other changes mades in the long run !
