### ISSUE TITLE
Night mode not removed upon updating to 0.2

### ISSUE THREAD

**Issue by ifeign** [EHylands/homebridge-qolsys#10]
I totally appreciate you removing the useless night mode, but after updating to 0.2 it’s still there. I haven’t tried removing and re-adding yet because it’s a pain, but maybe you can shed some light on this before I take that step

**Comment by EHylands** [comment]
> I totally appreciate you removing the useless night mode, but after updating to 0.2 it’s still there. I haven’t tried removing and re-adding yet because it’s a pain, but maybe you can shed some light on this before I take that step

Unfortunately, you can't make any changes to an accessory allready added to HomeKit. It needs to be removed and added again.

You have to:
- uncheck ´Show security panel'
- Restart Homebridge
- check ´Show security panel'
- Restart Homebridge

It did worked in my case. Please let me know afterwards.

I just received my IQ2+ panel yesterday. I tried testing most possibilities. 

Found out accessories (security panel) was not in sync with panel at start up so fixed that.

Last thing I found out is that, unless exit delays are set to 0 sec, you can't switch from arm stay directly to arm away without disarming first. Currently thinking about the best work around for that situation.

**Comment by ifeign** [comment]
Fixed. Thank you. May be worth noting as a breaking change for this version. Now to add it back to my scenes and automations..
