### ISSUE TITLE
6 digit code only

### ISSUE THREAD

**Issue by ojoaosemtil** [EHylands/homebridge-qolsys#11]
Hello!
Thank you very much for this plug-in!
I have a Qolsys 2+ I guess, and I wonder if it is possible to use it with only the 4 digit code, instead of 6?

Thank u!

**Comment by EHylands** [comment]
Hi @ojoaosemtil ,

The 6 digit code is a requirement by some IQ Panel firmware prior to enabling 3rd party integration. People on Home Assistant forum have reported being able to revert back to 4 digit code after enabling 3rd party integration. This may only have been possible with older firwmare (TBD)

The plugin by itself will work fine with either 4 or 6 digit code (I am running myself an IQ2+ Panel on 2.6.1 firmware with 4 digit code)

Just received my IQ Panel 2 days ago. Still trying to get it to upgrade past 2.6.1. Will report back as soon as I can get 2.6.2 running on it.

**Comment by ojoaosemtil** [comment]
I did that, reverted to 4 digit and I can’t do anything because the plug-in asks for the 6 digit code, do you think it is something that you can’t do anything about?

**Comment by EHylands** [comment]
Are you sure you are not running an IQ4 Panel ? 
2.7.1 is the lastest firmware I am aware on IQ2+ panel.
In your case, 4.2.0 is the lastest firmware update for IQ4 panels.

Please look at the IQ4 Panel to see if it is your model.
[https://qolsys.com/iq-panel-4/](https://qolsys.com/iq-panel-4/)

I am not aware of anyone running and IQ4 Panel who could revert back to 4 digit code.

**Comment by ojoaosemtil** [comment]
You’re right! It’s an IQ4 sorry, my fault!
So it’s a limitation of the panel, I get it..

**Comment by EHylands** [comment]
> You’re right! It’s an IQ4 sorry, my fault! So it’s a limitation of the panel, I get it..

I would say it is a security feature :P 
From a security point of view, I think it would have been trivial to brute force a 4 digit code for anyone having your secure token. 

WIll reporte back in documentation as soon as I can update my IQ2+ panel.
Some IQ2-IQ2+ ppanel may be able to revert back to 4 digit code
I am not aware of any IQ4 Panel reverting back to a 4 digit code.

Will be closing this issue for now.

Tnx !

**Comment by ojoaosemtil** [comment]
Ahah yes, mora a security feature than a limitation, thank you very much for your time!
