### ISSUE TITLE
Arm away acting weird

### ISSUE THREAD

**Issue by ifeign** [EHylands/homebridge-qolsys#12]
Arming away has been acting up, when I arm via HomeKit, it says arming for about a minute and then ultimately sets the system to Home. Unfortunately I'm traveling and don't have remote access to logs (I need to get reverse proxy working again soon).

**Comment by EHylands** [comment]
Hi,
I think you may have the "Auto Stay" feature enabled on your panel in section "SECURITY AND ARMING":

"If panel is armed Away but a delay door is not opened, the panel assumes you are still home and changes arming to Stay Home"

Either disable this option or set Exit Delay to 0 sec. 

Let me know if that was the case.

EH

**Comment by EHylands** [comment]
<img width="756" alt="Screenshot 2023-01-12 at 3 02 58 PM" src="https://user-images.githubusercontent.com/90003064/212169301-eded0471-2cd7-49b6-a3db-7bcc177e6fdb.png">

**Comment by ifeign** [comment]
> Hi,
> 
> I think you may have the "Auto Stay" feature enabled on your panel in section "SECURITY AND ARMING":
> 
> 
> 
> "If panel is armed Away but a delay door is not opened, the panel assumes you are still home and changes arming to Stay Home"
> 
> 
> 
> Either disable this option or set Exit Delay to 0 sec. 
> 
> 
> 
> Let me know if that was the case.
> 
> 
> 
> EH
> 
> 
> 
> 

You might be on to something with this. I could swear I disabled this previously but it's possible the setting was reset when I did a firmware update recently. I'll have to check when I return from my trip

**Comment by EHylands** [comment]
For the second part of you question:
While the panel is in Exit Delay:

`HomeKit Current State = DISARM
HomeKit Target State = ARM`

This is why "Arming ..." is running a the top of the Homekit acccessory for the duration of the Exit Delay period.

At the end of the Exit Delay period, when the panel is armed:

`HomeKit Current State = ARM
HomeKit Target State = ARM`

Then you get all the HomeKit notifications confirming that the Panel is armed.

An alternative method would be to set Homekit Current State to ARM during the Exit Delay period and you would get an immediate Homekit Notification.

If the panels fails to arm, you get and HomeKit notification when the panel gets back in a Disarmed state.

This could be set through a config option if people are interested (Partition Early Arm ?)

**Comment by ifeign** [comment]
Turns out auto stay was on. Changing that and setting exit delay to 0 (which is how my old hass plugin was configured) has put things back the way I like them. Thanks again!

**Comment by EHylands** [comment]
Glad to see it was only a small configuration error!
