### ISSUE TITLE
Wrong associated ARMING_MODE when panel is in ENTRY_DELAY

### ISSUE THREAD

**Issue by EHylands** [EHylands/homebridge-qolsys#14]
To replicate:
Panel in ARM_STAY mode
Panel enters ENTRY_DELAY
Homekit shows Panel as ARM_AWAY and then proceed to show panel in DISARM mode

Fix pending !

**Comment by MistyMoose** [comment]
Thank you! 

Unrelated, but interesting that there is "exit delay" mode for Arm-Stay. To my knowledge the IQ panel doesn't have an exit delay for stay mode.

**Comment by EHylands** [comment]
> Thank you!
> 
> Unrelated, but interesting that there is "exit delay" mode for Arm-Stay. To my knowledge the IQ panel doesn't have an exit delay for stay mode.

I think it is user configurable.
On my IQ2+ panel, there is an exit delay state to enter ARM_STAY

**Comment by EHylands** [comment]
@MistyMoose , you can try beta version 0.2.6.
Proper Arming mode is kept while entering Entry Delay.

**Comment by MistyMoose** [comment]
Tested & confirmed. Works great! Thank you very much.
