### ISSUE TITLE
Great plugin - one question

### ISSUE THREAD

**Issue by visionik** [EHylands/homebridge-qolsys#17]
Hi - Just installed.  Works great.  You might want to mention in your readme that once you enable Control4 automation, you have to run your HomeBridge plug-in within 10 minutes.  After 10 minutes with no Control4 "registration", the IQ panel disables Control4 and reboots.  This is mentioned here: https://qolsys.reamaze.com/kb/faqs-for-iqp2/how-to-integrate-your-iq-system-with-control-4

Request - do you have any idea if the Qolsys <--> Control4 integration can support ZWave devices connected to the Qolsys panel via ZWave? 

I have a Qolsys flood sensor / water valve kit.  The flood sensors work with the plugin as they are Qolsys S-Line devices.  The water valve is a ZWave device that you can send and OPEN or CLOSE command to.

**Comment by EHylands** [comment]
> Hi - Just installed.  Works great.  You might want to mention in your readme that once you enable Control4 automation, you have to run your HomeBridge plug-in within 10 minutes.  After 10 minutes with no Control4 "registration", the IQ panel disables Control4 and reboots.  This is mentioned here: https://qolsys.reamaze.com/kb/faqs-for-iqp2/how-to-integrate-your-iq-system-with-control-4

Thank you for pointing that out. I will update the readme file.

> 
> 
> 
> Request - do you have any idea if the Qolsys <--> Control4 integration can support ZWave devices connected to the Qolsys panel via ZWave? 

Qolsys C4 integration hasn't been updated since 2019. It doesn't support any ZWave function unfortunately.

https://drivers.control4.com/solr/drivers/browse?&q=&fq=manufacturer:%22Qolsys%22

> 
> 
> 
> I have a Qolsys flood sensor / water valve kit.  The flood sensors work with the plugin as they are Qolsys S-Line devices.  The water valve is a ZWave device that you can send and OPEN or CLOSE command to.
> 
> 
> 
>

**Comment by cistearns** [comment]
> Thank you for pointing that out. I will update the readme file.

I added this note to the readme. In my experience the delay on the timeout is 15 minutes - but this is probably firmware dependent. Either way I think you can call this documented and close the issue.
