### ISSUE TITLE
Can't Arm Away

### ISSUE THREAD

**Issue by Omar-L** [EHylands/homebridge-qolsys#18]
## Issue
From the Home app, when I set the system to Arm Away it will say 'Arming...' but eventually it sets itself to **Stay** instead of **Away**. 

When I arm the system for **Away** from the Alarm.com app the Home will reflect the system as **Away**. 

## Version
Plug-in version: `homebridge-qolsys v0.3.0 `

Panel model: Qolsys IQPanel 2+

## Logs
Will provide soon...

**Comment by EHylands** [comment]
Hi,
Try disabling the Auto Stay option.

With that option enabled, After arming , panel will automatically reverts to Arm Stay if no delay door is opened.

![image](https://github.com/EHylands/homebridge-qolsys/assets/90003064/cd757628-3893-4a24-99e7-e8e3bc7f8806)

Let me know if it helps !

**Comment by Omar-L** [comment]
This is the root cause of the issue. I was able to fix it in the panel settings. Thank you.
