### ISSUE TITLE
Qolsys Tilt sensor should map to HomeKit contact sensor

### ISSUE THREAD

**Issue by cistearns** [EHylands/homebridge-qolsys#20]
Currently the Qolsys tilt sensor, for garage doors, is failing to map to HomeKit as it gets flagged as Unknown. It can just be mapped to a contact sensor for purposes of HomeKit.

Debug info for the Zone in question:
{"id":"xxxxxx","type":"Tilt","name":"Garage Tilt","group":"garageTilt2","status":"Closed","state":"0","zone_id":5,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":16,"partition_id":0}

**Comment by EHylands** [comment]
Added Tilt sensor with you pull request.
Also added a 'Show Tilt Sensors' option in Homebridge UI.
