### ISSUE TITLE
Night Mode reappears in iOS 17

### ISSUE THREAD

**Issue by ojoaosemtil** [EHylands/homebridge-qolsys#25]
Hello,
With iOS 17, the Night Mode reappears in the Home app, do you think it will be possible to remove it again, in the future?

**Comment by cistearns** [comment]
If you attempt to arm as Night, does it still arm the panel as Stay?

It wouldn't be too bad if Night just maps to Stay when used from the Home side of things, especially if other parts of home use that to key other actions.

**Comment by ojoaosemtil** [comment]
When arming to Night, if the panel is in Home mode it reverts to Home, if it’s Off it reverts to Off.

**Comment by cistearns** [comment]
Yeah, if it's not possible to remove it as an option, it might be easier to just map it in the plugin to Stay, just a thought.  Broadly, even on security panels that support Night as a distinct mode the differences between that and Stay usually only applies to sensors with a specific 'Night' zone type.

**Comment by EHylands** [comment]
Installed iOS 17 and fired my Qolsys test panel.
The plugin code was already mapping Homekit Night mode to Qolsys Arm Stay.

In current version on iOS 17:
Night mode button is visible in Homekit but doesn't generate any event on iOS side when pressed. 
Button is visible but inactive.

It has been reported by other users on Discord Homebridge forum. 

Other Homekit accessories mode hiding features still work the usual way. iOS bug is suspected.

**Comment by cistearns** [comment]
Is there any indication if a removing and reconnecting the bridge to HomeKit resolves changes this behavior?  (ie is this a bug with existing configurations before 17 or all 17 installs.)

**Comment by EHylands** [comment]
> Is there any indication if a removing and reconnecting the bridge to HomeKit resolves changes this behavior?  (ie is this a bug with existing configurations before 17 or all 17 installs.)

I tried removing and adding the Security system without any changes.

Will try removing the bridge tonight and report back.

**Comment by EHylands** [comment]
> Is there any indication if a removing and reconnecting the bridge to HomeKit resolves changes this behavior? (ie is this a bug with existing configurations before 17 or all 17 installs.)

Same issue after reconnecting the bridge ...

**Comment by ifeign** [comment]
This appears to be fixed in iOS 17.1

**Comment by cistearns** [comment]
Confirmed that this is resolved in 17.1.
