### ISSUE TITLE
Heat Detectors Not Recognized

### ISSUE THREAD

**Issue by maxiboch** [EHylands/homebridge-qolsys#27]
Hi! 

I was just hoping you might be able to get this sensor type working, as it's essentially the same as the smoke detector type, and ideally would just be treated as such. Here's the debug output with the relevant strings:

{"id":"101-5555","type":"Heat","name":"2nd Floor Heat Detector","group":"smoke_heat","status":"Closed","state":"0","zone_id":28,"zone_physical_type":10,"zone_alarm_type":0,"zone_type":8,"partition_id":0}

Let me know if there's any other info you need. Thanks! So grateful to you for the robust local version of this integration!

**Comment by maxiboch** [comment]
Wow you are fast! Can confirm it's working on the v0.4.1-beta.1 branch.

**Comment by EHylands** [comment]
> Wow you are fast! Can confirm it's working on the v0.4.1-beta.1 branch.

Great ! 
Thank you for testing.
Will issue formal version 4.1
