### ISSUE TITLE
Doorbell notification support

### ISSUE THREAD

**Issue by ifeign** [EHylands/homebridge-qolsys#32]
It appears that the equivalent HASS plugin has figured out doorbell press notifications, would it be possible to add this so that we can get doorbell notifications? It should be possible to use HomePods as chimes if this can be implemented 

https://github.com/XaF/qolsysgw/issues/102

**Comment by EHylands** [comment]
Hi @ifeign,
I added the Doorbell sensor accessory to version 0.5.0-beta.0
I don't own a IQ Doorbell sensor myself, but I was able to add a simulated doorbell accessory to home app and get iOS notification on doorbell ring.
Please let me know if it works on your side.

**Comment by EHylands** [comment]
![image](https://github.com/EHylands/homebridge-qolsys/assets/90003064/1b08e75d-d0e3-4bc7-83d0-c00a342944c2)

**Comment by ifeign** [comment]
Oh wow I’m a fool and missed that this requires the IQ sensor. I thought this would work with my ADC-VDB770. Guess I’ll pick up one of these sensors, thanks for adding this!

**Comment by EHylands** [comment]
@ifeign 
I just saw your new reply.
I don't own an HomePod yet.
Doorbell accessory doesn't look like its adding an accessory in Home App. I see the doorbell accessory in Homebridge but only doorbell notifications in Home App.

Was the example shown from your ADC-VDB770 accessory?

I will try to find out differences between doorbell accessory and video doorbell accessory.

**Comment by ifeign** [comment]
> @ifeign I just saw your new reply. I don't own an HomePod yet. Doorbell accessory doesn't look like its adding an accessory in Home App. I see the doorbell accessory in Homebridge but only doorbell notifications in Home App.
> 
> Was the example shown from your ADC-VDB770 accessory?
> 
> I will try to find out differences between doorbell accessory and video doorbell accessory.

The example is just a generic screenshot from an article on HomeKit doorbells

**Comment by cistearns** [comment]
Just a couple added notes. The IQ Doorbell sensor is likely just a regular sensor configured to detect when the circuit for a door bell is completed, kind of like a water sensor. @EHylands I assume you simulated it by just using a regular contact sensor, and telling the IQ panel that it is a doorbell sensor? If not that should be possible to basically see it end to end, it is going to be a normally open sensor and when the contact is closed is the button press.

Due to how it works and how most doorbell cameras work, the sensor is likely not compatible with using a doorbell camera _unless_ the camera is also using a power kit that bypasses the physical chime until the button is pressed. @ifeign if your VDB770 doesn't have the power kit you will likely need one for this to work.

I'll be curious to see how well this works. I've been using a IQ Remote to know when the doorbell is pressed in another part of the house.

**Comment by ifeign** [comment]
> Just a couple added notes. The IQ Doorbell sensor is likely just a regular sensor configured to detect when the circuit for a door bell is completed, kind of like a water sensor. @EHylands I assume you simulated it by just using a regular contact sensor, and telling the IQ panel that it is a doorbell sensor? If not that should be possible to basically see it end to end, it is going to be a normally open sensor and when the contact is closed is the button press.
> 
> Due to how it works and how most doorbell cameras work, the sensor is likely not compatible with using a doorbell camera _unless_ the camera is also using a power kit that bypasses the physical chime until the button is pressed. @ifeign if your VDB770 doesn't have the power kit you will likely need one for this to work.
> 
> I'll be curious to see how well this works. I've been using a IQ Remote to know when the doorbell is pressed in another part of the house.

Considering that the sensor is battery powered, I’m not concerned about it drawing power away from my existing video doorbell. It attaches to the chime and behaves as you described, by notifying once the chime circuit is completed. I will report back once I receive the sensor on whether or not my video doorbell has power issues. I only want this sensor to be able to turn my HomePods into chimes…

**Comment by cistearns** [comment]
@ifeign The compatibility issue between door bell cameras and the sensor is that the small constant current pull from the camera may be enough that the sensor will detect that as button presses, generating random phantom presses. This will depend on its sensitivity threshold. An inline resistor  on the sensor may help if that is the case. The reason the power kits can resolve this is that it  isolates the chime so that current only flows to the physical chime when the button is pressed (this is also why it is used to eliminate buzzing of the chime).
If you already have a power kit then just attach the IQ sensor only to the physical chime and it should work without issue.

**Comment by ifeign** [comment]
From my understanding of the vdb770 user manual, the power kit is mandatory
anyway. I’ll investigate later today. Thanks your your insight, it’s very
helpful

**Comment by cistearns** [comment]
Just a heads up but I tried to get my hands on the IQ Doorbell sensor, and it sounds like they may no longer be in production. I'm going to try another vendor that might have old stock.

**Comment by ifeign** [comment]
> Just a heads up but I tried to get my hands on the IQ Doorbell sensor, and it sounds like they may no longer be in production. I'm going to try another vendor that might have old stock.

Just sourced one on eBay! Will report back once I have it. Canceled my AlarmGrid order because it was backordered

**Comment by cistearns** [comment]
@ifeign yeah, it was AlarmGrid that got back to me and canceled the order to due to lack of availability. Currently I don't see any on eBay, so these may just be very hard to source going forward, which is unfortunate, but expected since doorbell cameras are a common install now.

**Comment by ifeign** [comment]
I was shipped a faulty sensor, very disappointed. The LED on the sensor don’t light up at all, and it is never detected by the panel even after a battery swap. The search continues. Any luck? @cistearns

**Comment by cistearns** [comment]
@ifeign Nope I never found one. Maybe grab a picture of the internals?  It's possible these are functionally just flood sensors, which are also a normally open sensor. Normally the panel doesn't really care if you force the sensor to a different type as long as the normal state is the same as needed for that type.

**Comment by ifeign** [comment]
![image](https://github.com/EHylands/homebridge-qolsys/assets/32289760/1718c948-16a1-4c95-984d-cfb84f4e07ce)
I ordered another one from a site called CommGear after confirming they had stock. Shipping was a bit steep, but I really want this damn sensor. Will try again next week once it gets in

**Comment by cistearns** [comment]
Ahh, yeah it has 3 wires instead of two so it is different internals.

**Comment by ifeign** [comment]
The third wire (white) is optional and is only for if you have a second
rear doorbell

**Comment by ifeign** [comment]
Well I added the sensor, and it shows up in HomeKit like this
![image](https://github.com/EHylands/homebridge-qolsys/assets/32289760/0e9cf04c-4387-4d0e-b7ba-ae86f5c837db)

I also don’t get doorbell notifications. Did I do something wrong on my end @EHylands?

**Comment by cistearns** [comment]
@ifeign can you confirm what version your HomeKit hub device is running? (ie 17.x)

**Comment by ifeign** [comment]
It's the latest 17.x release, I always keep it updated. I've run into a problem though, these damn sensors are a pain. I got it paired with my panel, but it wasn't doing anything, it wouldn't even notify of a tamper like any other sensor would.. so I unpaired it and now it refuses to pair with the Qolsys panel again. I am about to give up lol. There's basically zero documentation on this thing and I can't be sure how to factory reset it - nothing I've tried works

**Comment by cistearns** [comment]
@ifeign S-Line sensors like this are basically dumb one way communication devices, they don't have a concept of factory reset, the panel can just learn them in when they are tampered due to the messages they send. Since these are old stock I'd assume the batteries are bad in them, even if the pull tabs are still in place. You can also directly learn them in using their identifier rather than autolearn though that info using gets covered up with the mounting tape. 

Along with swapping out batteries you might try to tamper while not attached to the doorbell, in case there is something about the existing current at the doorbell that is messing it up. If it does install detached you should be able to test it by just touching the red and black wires or the white and black wires.

It's possible that these are just prone to failure.

**Comment by ifeign** [comment]
I changed the batteries and tried your steps. No luck so far. I can’t even manually pair because I don’t seem to have the any ID that works. All of mine have letters in them which the panel does not let me type

![image](https://github.com/EHylands/homebridge-qolsys/assets/32289760/5e8f821f-9656-48b8-9d4b-0bb058a4fc8c)
![image](https://github.com/EHylands/homebridge-qolsys/assets/32289760/dacd6d7f-7661-44db-bd38-6367c3eba241)

**Comment by cistearns** [comment]
So the problem is that it is being added at as a PowerG sensor, when it is an S-Line Sensor. I don't know how that is happening, but it won't work as a PowerG (345Mhz) sensor
The Source should be RF319 (it's a 319.5 MHz device. That is also why you couldn't enter a DL ID for it correctly.

Maybe confirm what sensor radios you do have?  The IQ2 comes in a few flavors and not all support S-Line sensors.
If you aren't sure look up the Part Number to System Configuration under Advanced -> About -> Hardware.

**Comment by cistearns** [comment]
@ifeign Actually relooking at your screen shots, I'm almost certain your configuration is that of a PowerG+345. This means that it is configured to work with PowerG sensors as well as 2Gig / Honeywell sensors, but not S-Line or Interlogix (319Mhz). In which case this sensor won't work for you. The 'good' news is that if you can find a legacy 345Mhz 2Gig/Honeywell sensor that does the same thing you can try to use that.

**Comment by ifeign** [comment]
Yes I have a PowerG + 345. If this sensor is incompatible, why is it able to connect? My issue might actually be from distance to the doorbell chime (it’s on the second floor). My signal strength is terrible

![image](https://github.com/EHylands/homebridge-qolsys/assets/32289760/67158006-be7b-4152-83b4-ac084e9dcd90)

**Comment by cistearns** [comment]
When adding it, was the sensor detected as a doorbell or did you have to change the type to doorbell?  It's entirely possible you are just picking up some other sensor from a distant neighbor that is in a trouble/broadcast state so the panel is trying to add it.

Either way I think you are unfortunately out of luck with this device.  There are a few hack approaches you can try, if you get your hands on a sensor that has auxiliary contact terminals to use to detect the doorbell being triggered. The PowerG PG9945 is an example, though you can probably get something cheaper in the legacy 2Gig/Honeywell sensors.

**Comment by cistearns** [comment]
@ifeign did you get the daughter board?  I think installing it means pulling out the 345 board, so you will want to make sure you don't have any sensors on the 345.

**Comment by ifeign** [comment]
> @ifeign did you get the daughter board? I think installing it means pulling out the 345 board, so you will want to make sure you don't have any sensors on the 345.

It should get in tomorrow. I don’t have any 345 accessories, so I’m hoping this is the final hurdle. Tested my sensors with my Flipper Zero (idk why I didn’t think to sooner) and both are broadcasting at 915.5mhz, so I guess I have a spare now if you’d like it.

Anyway, will report back soon

**Comment by ifeign** [comment]
It works perfectly! No extra accessories show up in the app, it just immediately works after restarting my Qolsys child bridge

**Comment by ifeign** [comment]
Looks like I spoke too soon. I had to restart the server Homebridge is installed on yesterday, afterwards a “not supported” doorbell accessory appeared. Not a huge deal, @EHylands is it worth reopening this issue? Or is this just what has to happen to have a functional doorbell sensor?

**Comment by EHylands** [comment]
Hi,
I'm glad to know the doorbell trigger mechanism works properly.

I have tried to properly set the accessory characteristics for the unsupported tile to disappear in Home app without success yet. I tried looking into other homebridge projects only using a doorbell without an associated video camera but couldn't find one yet.

The other option I found (on a version I did not publish yet) is to present the doorbell accessory in Home app as a stateless button. It allows to configure an automation or a scene when the doorbell is triggered through the native home app without resorting to a 3rd party app line Eve. 

I could publish that version if you would like to try that second option.

**Comment by ifeign** [comment]
> Hi, I'm glad to know the doorbell trigger mechanism works properly.
> 
> I have tried to properly set the accessory characteristics for the unsupported tile to disappear in Home app without success yet. I tried looking into other homebridge projects only using a doorbell without an associated video camera but couldn't find one yet.
> 
> The other option I found (on a version I did not publish yet) is to present the doorbell accessory in Home app as a stateless button. It allows to configure an automation or a scene when the doorbell is triggered through the native home app without resorting to a 3rd party app like Eve.
> 
> I could publish that version if you would like to try that second option.

A stateless button would be amazing actually! I could have my TV pause when the doorbell is pressed for example. Only example non-video plugin I can think of is [this one](https://www.npmjs.com/package/homebridge-fake-doorbell)

**Comment by EHylands** [comment]
@ifeign , I just published version 0.5.0-beta.1 with a stateless button.
Let me know if it works!

**Comment by ifeign** [comment]
> @ifeign , I just published version 0.5.0-beta.1 with a stateless button. Let me know if it works!

@EHylands it works perfectly! I just created a test action to turn off some lights, worked immediately.

I think this is ready for release

**Comment by ifeign** [comment]
One final question @EHylands is this icon an option for buttons? Or did they change when they updated all the icons for iOS 16?

![IMG_2386](https://github.com/EHylands/homebridge-qolsys/assets/32289760/e511b98d-e8c2-4a4c-af4a-42e0c5e9c395)

**Comment by EHylands** [comment]
@ifeign I tried playing around with the accessory characteristics, but could not find a way to change the tile icon in Home app ...
