### ISSUE TITLE
[QolsysPanel] Panel Connection Error (read ECONNRESET)

### ISSUE THREAD

**Issue by morningla** [EHylands/homebridge-qolsys#33]
my IQ2 panel added the first time, then after a little bit, I keep getting this error.  I generated a new secure token, restarted everything, still the same...   too many requests?  my panel is not connected to any monitoring companies.

**Comment by cistearns** [comment]
I think that error usually means the plugin can't even open the network socket - which means the panel simply isn't reachable.

Double check that the Connect4 integration is still enabled and that your wifi connection is still up. There are a few ways Control4 can become disabled on its own, if the panel or server lost power for any length of time, or the panel had a firmware upgrade.

**Comment by morningla** [comment]
thanks, it needed some homebridge/windows restart, and panel reboot.  after a while, it settled down and is stable now.
________________________________
