### ISSUE TITLE
Freeze sensor support

### ISSUE THREAD

**Issue by cistearns** [EHylands/homebridge-qolsys#34]
IQ panels support a Freeze sensor that from an event standpoint operates like a contact sensor, when it goes below a specific temperature (40F) it trips the sensor Open, and Closes on restore when the temp returns above 40F.

I don't know if there is a good equivalent in HomeKit support since the sensor doesn't actually report a temperature, so this may be a case of adding it to ignore it like with Keypad and Bluetooth. Maybe optionally allow people to map it to a contact sensor so they can setup alerts in HomeKit, or ignore it.

Example debug output:
{"id":"8950A4","type":"Freeze","name":"Basement Freeze","group":"freeze","status":"Closed","state":"0","zone_id":53,"zone_physical_type":6,"zone_alarm_type":0,"zone_type":17,"partition_id":0}]}

**Comment by EHylands** [comment]
homebridge-qolsys@0.5.0-beta.2

Added Freeze sensor as an optionnal contact sensor like you suggested.

**Comment by ifeign** [comment]
Wow perfect timing because I just got a flood/freeze sensor. Will test too

**Comment by cistearns** [comment]
Tested, it is working as expected. @EHylands I think this is good to merge and spin an official release.
![IMG_1502](https://github.com/EHylands/homebridge-qolsys/assets/16590166/c73878fb-09ab-43ee-bdb1-415003454940)
![IMG_1503](https://github.com/EHylands/homebridge-qolsys/assets/16590166/3fa859b4-a28b-421e-bf83-9fd09a6a9315)
