### ISSUE TITLE
Not an issue, but question about going with Qolsys or PROA7PLUS with native HomeKit for new system

### ISSUE THREAD

**Issue by JoeBlowGH** [EHylands/homebridge-qolsys#37]
Apologies in advance, this isn't an issue, but more of a question.

If you were starting fresh, looking for a centrally monitored security system, would you opt to go with the PROA7PLUS with native HomeKit integration or a Qolsys IQ4 and use Homebridge for HomeKit integration?  From a purely security standpoint, the Qolsys panel is more attractive to me due to its support for PowerG sensors with frequency hopping. Additionally, it seems like a majority of people prefer the interface of alarm.com over HW Total Connect.

I love what you've already done with the Qolsys panel here, but I'm nervous about the long term viability.  What if you all lose interest in maintaining this?  Or, how often will issues pop up when iOS is updated or the panel firmware is updated?  I don't mind using the native app for the home security related items, but it would suck to lose all the door/window sensor automation in HomeKit.  I've read one person saying that with the PROA7PLUS, the sensors aren't exposed to HomeKit when the system is armed.  If true, I don't like that.

One thing that would be nice to see exposed here is the additional arming options for bypass, exit sounds and entry delay, with entry delay being the biggest improvement for me.  I like having no entry delay at night, so as soon as a sensor is tripped, the alarm goes off.

**Comment by cistearns** [comment]
A forum on Reddit is may be a better place to ask this question if you want to get more options on the Residio panel and monitoring using Total Connect.

Options for bypass, exit sounds and entry delay are all configured directly at the panel and not through Control4 protocol. Support here is limited by what is exposed via Control4.

It is always a risk that this plugin could become broken if Qolsys decides to eliminate Control4 support, though that seems unlikely.

Personally I think the only reason to have HomeKit integration with a panel is specifically for the sensor statuses to enable additional automation options (or if it also exposes any other panel devices). I generally don't use HomeKit for any Arm/Disarm functionality. HomeKit itself doesn't really provide much interesting functionality around the panel arm state, the concept of Security Panels in HomeKit feels mostly like an after thought.

**Comment by JoeBlowGH** [comment]
Thanks, Charles.  I really appreciate your response, it's been helpful!  I did post on Reddit, but got very little feedback, so thought that maybe the group of people here, the actual users and developers of the integration, would have a better view.

I do agree with you that the sensor statuses are by far more important to me in HomeKit for automations than the security functions themselves.  The added ability to have a scene arm the alarm is a "nice to have" bonus, but by no means a requirement.  I just don't want to invest thousands into a home security system, add 30+ window/door sensors, and then not be able to access those window/door sensors in HomeKit.

Thanks for the clarification re: what's exposed via Control4, I was missing that piece and it makes sense now.  I don't know what to think about Qolsys dropping Control4 support, but I take your point, and would tend to agree with you that it seems unlikely.  I really hope you and Eric don't give up on this!

**Comment by EHylands** [comment]
Hi, 
found the following review for PROA7PLUS Homekit features: [https://www.reddit.com/r/HomeKit/comments/15c34mx/psa_the_honeywellresideo_proa7plus_officially/](https://www.reddit.com/r/HomeKit/comments/15c34mx/psa_the_honeywellresideo_proa7plus_officially/)
Sensors and security status are available on both panels.

Please keep in mind that dealer code is necessary on Quolsys panel to enable C4 integration. Not everyone will provide you with that code unfortunatly!

**Comment by JoeBlowGH** [comment]
Thanks, Eric.  That was the Reddit thread that made me question the sensor availability when armed with the PROA7PLUS.  This comment:  "I also have HomeKit working on the Proa7plus. However, the HomeKit sensor detection stops working when the system is armed. Are you seeing this as well, or is there a setting or configuration for this?"

I found a another post of theirs, where I think what they're saying is it's just the motion sensors when armed in stay mode, presumably because those sensors don't report to the panel in stay mode.  Do you know if the motion sensors for the Qolsys panel still report motion to HomeKit when armed stay?

Regarding the dealer code, I would likely go with either Surety or AlarmGrid.  Guessing the code wouldn't be an issue with either of them, hopefully.

**Comment by cistearns** [comment]
The motion sensors still report events over Control4 into HomeKit. Not having seen how the sensors work in the Residio integration, I'd actually assume you will prefer the motion+occupancy configurable behavior defined in this plugin. By default security motion sensors don't work great for occupancy which is why the tunable behavior exists here.

I haven't used the PROA7PLUS personally, and my Honeywell experience is a bit stale (mostly Vistas), but it wouldn't surprise me if the motion sensor event reporting behavior going on there is based on the zone configuration for those devices.

**Comment by ifeign** [comment]
IMO the only reason to use this plugin plus a Qolsys panel is if you want to use unsupported sensors that have been shoehorned into HomeKit via some clever workarounds by the dev. For example the IQ-Doorbell sensor, or the freeze sensor which isn’t a native HomeKit thing, and is represented with a contact sensor. 

Otherwise, I’d take native over third party.. assuming it’s stable

**Comment by JoeBlowGH** [comment]
> IMO the only reason to use this plugin plus a Qolsys panel is if you want to use unsupported sensors that have been shoehorned into HomeKit via some clever workarounds by the dev. For example the IQ-Doorbell sensor, or the freeze sensor which isn’t a native HomeKit thing, and is represented with a contact sensor.
> 
> Otherwise, I’d take native over third party.. assuming it’s stable

I consider PowerG to be more secure than PROSiX.  I don't need the range, but the FHSS with PowerG is more secure IMO.  That's the only thing pushing me to Qolsys over Honeywell.  That and it seems like alarm.com has a better app experience.  First and foremost the security system should provide security, with automation a second thought.

My planned automations are pretty simple (for now), lights tied to doors and motion sensors, thermostat tied to window sensors.  The first I could probably do for low cost with additional dedicated sensors should this plugin ever stop working.

**Comment by JoeBlowGH** [comment]
Thanks all for your feedback, I ended up ordering the Qolsys panel.  Looking forward to trying out the plugin.
