### ISSUE TITLE
Confirm Homebridge 2.0 Support

### ISSUE THREAD

**Issue by mmenanno** [EHylands/homebridge-qolsys#41]
Could you test if this plugin will work in Homebridge 2.0?

![image](https://github.com/user-attachments/assets/14584880-3e2c-4c9b-8908-5ba246056293)

Notably once the plugin is tested for v2.0, updating the `package.json`'s `engines.homebridge` value is how this plugin can get that green check.

https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0#homebridge-v2

**Comment by EHylands** [comment]
Hi,
I updated the package.json file for Homebridge 2.0 support.
There should not be any changes in Homebridge 2.0 impacting on this plugin.
You can try homebridge-qolsys-0.5.1-beta.1 and report back.
Tnx

**Comment by mmenanno** [comment]
Amazing, checked the beta and the warning is now gone. Thanks!

![image](https://github.com/user-attachments/assets/f8cdc404-92e5-4f64-a545-d857657765b7)
