### ISSUE TITLE
Port Number? 

### ISSUE THREAD

**Issue by anthonyb82** [EHylands/homebridge-qolsys#5]
Hi there! Trying to give this a test drive. Where do I get the port number for the panel? Thanks in advance.

**Comment by EHylands** [comment]
> Hi there! Trying to give this a test drive. Where do I get the port number for the panel? Thanks in advance.

Hi,
By default, 3rd party integration is running on port 12345.

Need to enable 3rd party integration on panel first with dealer's code.

Will work on providing better documentation since plugin is now working !

**Comment by anthonyb82** [comment]
Thanks for the quick response. Ok, that is how I set it up but for some reason I’m not seeing my panel info on home. Thought the port number might be the issue. I followed the 3rd party integration and dealer code instructions and all that seems correct. I’m not noticing anything in my Homebridge logs indicating an error, but also not seeing it pulling any sensor info. 

I’m certainly not an expert at all of this, so if there is a simple thing I perhaps am overlooking, please let me know. Otherwise I’ll just slide back out to not cause you any headaches 😊

**Comment by EHylands** [comment]
Which panel are you using ? Some people reported on Home Assistant forum that they had to reenable 3rd party integration on Qolsys panel a few times before it stayed on.

Make sure to properly enter your secure token in plugin configuration page.

You can try running Homebridge in debug mode with -D flag to get detailed plugin information.

At some point, you should get the following output in your logs if working properly:

`[12/26/2022, 8:27:14 PM] [QolsysPanel] Panel now ready for operation [12/26/2022, 8:27:14 PM] [QolsysPanel] ----------------------------------------- [12/26/2022, 8:27:14 PM] [QolsysPanel] Qolsys Panel Information [12/26/2022, 8:27:14 PM] [QolsysPanel] ----------------------------------------- [12/26/2022, 8:27:14 PM] [QolsysPanel] Partition0: Partition1 [12/26/2022, 8:27:14 PM] [QolsysPanel] Zone1: RC Motion [12/26/2022, 8:27:14 PM] [QolsysPanel] Zone2: RC Window [12/26/2022, 8:27:14 PM] [QolsysPanel] Zone3: Garage Door [12/26/2022, 8:27:14 PM] [QolsysPanel] Zone4: Master Bedroom [12/26/2022, 8:27:14 PM] [QolsysPanel] Zone5: Basement window [12/26/2022, 8:27:15 PM] [QolsysPanel] ----------------------------------------- [12/26/2022, 8:27:15 PM] [QolsysPanel] Configuring Homebridge plugin accessories [12/26/2022, 8:27:15 PM] [QolsysPanel] ----------------------------------------- [12/26/2022, 8:27:15 PM] [QolsysPanel] Partition0(Security System): partition1 [12/26/2022, 8:27:15 PM] [QolsysPanel] Zone1 (MotionSensor): RC Motion [12/26/2022, 8:27:15 PM] [QolsysPanel] Zone2 (ContactSensor): Living Room Window 2 [12/26/2022, 8:27:15 PM] [QolsysPanel] Zone3 (ContactSensor): Garage Door [12/26/2022, 8:27:15 PM] [QolsysPanel] Zone4 (MotionSensor): Master Bedroom [12/26/2022, 8:27:15 PM] [QolsysPanel] Zone5 (ContactSensor): Door-Window 5 [12/26/2022, 8:27:15 PM] [QolsysPanel] ----------------------------------------- [12/26/2022, 8:27:15 PM] [QolsysPanel] Starting Controller Operation [12/26/2022, 8:27:15 PM] [QolsysPanel] -----------------------------------------`

You should also get some information on connection failure.

You can provide your log file if you want further assistance!

**Comment by anthonyb82** [comment]
Thank you. This is all I’m seeing in my logs. Any “x”’s are just edits I made here to protect info. The token in my actual logs matches what’s on my panel. Looks like 3rd party connections is still enabled on the panel. 

[12/30/2022, 12:27:59 PM] [homebridge-qolsys] Connecting: 192.xxx.xx.xxx.2345
[12/30/2022, 12:27:59 PM] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-qolsys) is running on port 30489.

[12/30/2022, 12:27:59 PM] [homebridge-qolsys] Sending: {"nonce":"","action":"INFO","info_type":"SUMMARY","version":1,"source":"C4","token":"1xxxxx"}
[12/30/2022, 12:27:59 PM] [homebridge-qolsys] Received: ACK

**Comment by anthonyb82** [comment]
Disregard this last message- I disabled and reenabled the 3rd party connection and then generated a new token from the panel. Everything showed up after that. Thanks so much!!

**Comment by EHylands** [comment]
> Disregard this last message- I disabled and reenabled the 3rd party connection and then generated a new token from the panel. Everything showed up after that. Thanks so much!! 

Great !
I will need yo do some tests to see if panel silently drops requests when wrong token is sent or if panel replies with an error. Will update documentation accordingly.
