### ISSUE TITLE
Homebridge verified plugin

### ISSUE THREAD

**Issue by ifeign** [EHylands/homebridge-qolsys#6]
Now that this plugin seems to fully work, you should get it verified, https://github.com/homebridge/verified

Your work deserves recognition!

**Comment by EHylands** [comment]
> Now that this plugin seems to fully work, you should get it verified, https://github.com/homebridge/verified
> 
> Your work deserves recognition!

I need to create an official GitHub release first for the verification process to be successful.

Will work on installation documentation tonight and create official release 0.1 afterward. 

Will subit to verification process!

Thank you !

**Comment by EHylands** [comment]
Plugin verification completed !

**Comment by ifeign** [comment]
Congrats!
