### ISSUE TITLE
Skybell notifications.

### ISSUE THREAD

**Issue by bluntiless** [EHylands/homebridge-qolsys#7]
Hi and thanks for creating this plugin. I just have a quick question not a real issue. 
Does this plugin send notifications from the Video doorbell, as I have been searching for a solution to trigger a doorbell notification in the Home App. Thanks

**Comment by EHylands** [comment]
Hi, unfortunately, Qolsys 3rd party integration is limited to basic features. 

From Command 4 driver documentation: This Driver supports the IQPanel2 for basic security. Supported features: Arming, Disarming, SRF Sensor Statuses, Emergencies, Partitions

The Command 4 driver hasn't been updated since 2019....

There is currently no z-wave device control or notifications in the protocol.

**Comment by bluntiless** [comment]
Ok thanks for your quick response. 
You have saved me a bit of time being spent, setting this up. 
I have been searching for a way to intercept the doorbell press notifications somehow. 
Back to the searches. Thanks again.

**Comment by EHylands** [comment]
Did you read the Home Assistant forum page in that regard ?

https://community.home-assistant.io/t/skybell-hd-component/21200

People resorted to tcpdumping encrypted connection between doorbell and server in the hope of speeding up the local notification speed...

Skybell public api for pushed notifications doesn't look to be available. Rate limited api pooling is useless in that situation...

**Comment by bluntiless** [comment]
Hi, yes I had a look at this in my countless searches. However I don't think this plugin is compatible with the Skybell I have, (ADC-VDB105X). It's from ADT in the UK and not registered with Skybell.

**Comment by ifeign** [comment]
I have an ADC-VDB770, doubt I'll ever get to integrate it with Homebridge. I plan on swapping out my cameras for Unifi Protect and simply using my alarm panel for contact sensors

**Comment by EHylands** [comment]
> This Driver supports the IQPanel2 for basic security. Supported features: Arming, Disarming, SRF Sensor Statuses, Emergencies, Partitions

@ifeign agree with you, updated the project readme file.
